CREATE TABLE `data_platform_freight_order_header_data`
(
	`FreightOrder`                              int(16) NOT NULL,
	`FreightOrderType`                          varchar(4) DEFAULT NULL,
    `PlannedFreight`                            int(16) NOT NULL,
    `FreightAgreement`                          int(16) NOT NULL,
    `FreightAgreementItem`                      int(6) NOT NULL,
    `FreightAgreementItemAvailableFreight`      int(4) NOT NULL,
    `FreightType`                               varchar(6) NOT NULL,
    `FreightSpec`                               varchar(6) NOT NULL,
    `FreightCalendar`                           varchar(6) NOT NULL,
    `PlannedFreightDepartureDate`               date NOT NULL,
    `PlannedFreightDepartureTime`               date NOT NULL,
    `PlannedFreightArrivalDate`                 date NOT NULL,
    `PlannedFreightArrivalTime`                 date NOT NULL,
    `ActualFreightDepartureDate`                date DEFAULT NULL,
    `ActualFreightDepartureTime`                date DEFAULT NULL,
    `ActualFreightArrivalDate`                  date DEFAULT NULL,
    `ActualFreightArrivalTime`                  date DEFAULT NULL,
    `SupplyChainRelationshipID`                 int(16) NOT NULL,
    `SupplyChainRelationshipDeliveryID`         int(6) NOT NULL,
    `SupplyChainRelationshipDeliveryPlantID`    int(4) NOT NULL,
    `SupplyChainRelationshipFreightID`          int(4) NOT NULL,
    `FreightPartner`                            int(12) NOT NULL,
    `Buyer`                                     int(12) NOT NULL,
    `Seller`                                    int(12) NOT NULL,
    `DeliverToParty`                            int(12) NOT NULL,
    `DeliverToPlant`                            varchar(4) NOT NULL,
    `DeliverFromParty`                          int(12) NOT NULL,
    `DeliverFromPlant`                          varchar(4) NOT NULL,
    `DeliveryDocument`                          int(16) NOT NULL,
    `PlannedFreightNumberInCharacter`           varchar(100) DEFAULT NULL,
    `PlannedFreightNumberDescription`           varchar(200) DEFAULT NULL,
    `ActualFreightNumberInCharacter`            varchar(100) DEFAULT NULL,
    `ActualFreightNumberDescription`            varchar(200) DEFAULT NULL,
    `FRPArea`                                   varchar(10) DEFAULT NULL,
	`FRPController`                             varchar(3) DEFAULT NULL,
    `FreightCapacityWeight`                     float(15) DEFAULT NULL,
    `FreightCapacityWeightUnit`                 varchar(3) DEFAULT NULL,
    `CreationDate`                              date NOT NULL,
    `CreationTime`                              date NOT NULL,
    `LastChangeDate`                            date NOT NULL,
    `LastChangeTime`                            date NOT NULL,
	`IsReleased`                                tinyint(1) DEFAULT NULL,
	`IsLocked`                                  tinyint(1) DEFAULT NULL,
	`IsCancelled`                               tinyint(1) DEFAULT NULL,
	`IsMarkedForDeletion`                       tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`FreightOrder`),
	
    CONSTRAINT `DPFMFreightOrderHeaderDataFreightAgreementItemAF_fk` FOREIGN KEY (`FreightAgreement`, `FreightAgreementItem`, `FreightAgreementItemAvailableFreight`) REFERENCES `data_platform_freight_agreement_item_available_freight_data` (`FreightAgreement`, `FreightAgreementItem`, `FreightAgreementItemAvailableFreight`),
    CONSTRAINT `DPFMFreightOrderHeaderDataPlannedFreight_fk` FOREIGN KEY (`PlannedFreight`) REFERENCES `data_platform_planned_freight_header_data` (`PlannedFreight`),
    CONSTRAINT `DPFMFreightOrderHeaderDataDeliveryDocument_fk` FOREIGN KEY (`DeliveryDocument`) REFERENCES `data_platform_delivery_document_header_data` (`DeliveryDocument`),
    CONSTRAINT `DPFMFreightOrderHeaderDataSCRFreight_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `SupplyChainRelationshipFreightID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`, `FreightPartner`) REFERENCES `data_platform_scr_freight_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `SupplyChainRelationshipFreightID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`, `FreightPartner`),
    CONSTRAINT `DPFMFreightOrderHeaderDataFreightFreightCapacityWeightUnit_fk` FOREIGN KEY (`FreightCapacityWeightUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`)


) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
